name: Проверка обязательного заполнения поля assignees

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка заполнения поля assignees
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const action = context.payload.action;

            // Пропускаем проверку для определенных действий, если необходимо
            if (action === 'labeled' || action === 'unlabeled') {
              // Вы можете добавить дополнительные условия здесь
            } else {
              if (!issue.assignees || issue.assignees.length === 0) {
                // Выводим сообщение об ошибке и отменяем изменение
                const owner = context.repo.owner;
                const repo = context.repo.repo;
                const issue_number = issue.number;
                const response = await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: issue_number,
                  body: "⚠️ Ошибка: Пожалуйста, назначьте ответственного за эту проблему. Поле `assignees` должно быть заполнено."
                });
                // Отменяем изменение, если assignees не заполнены
                throw new Error("Поле `assignees` не заполнено.");
              }
            }
