name: Create Issue in Project

on:
  # Выберите триггер, который будет запускать рабочий процесс, например, создание нового issue
  issues:
    types: [opened]

jobs:
  create_project_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create issue in project
        env:
          GITHUB_TOKEN: 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
        run: |
          # Идентификатор проекта
          PROJECT_ID=5
          # Получите идентификатор репозитория
          REPO_OWNER=phpshka
          REPO_NAME=test

          # Создайте новое issue
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues \
          -d '{
            "title": "Новое issue в проекте",
            "body": "Это issue было создано автоматически с помощью GitHub Actions.",
            "project": {
              "id": "'$PROJECT_ID'"
            }
          }'
